import { useEffect, useState } from 'react'
import { BarChart, Bar, Cell, CartesianGrid, ComposedChart, Line, Area, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getOverview, getRegions, getSKUs, runForecast } from './api'

const colors = ['#6ee7ff','#a78bfa','#34d399','#fbbf24','#fb7185']
const riskClass = { critical: 'critical', warning: 'warning', safe: 'safe' }

function Metric({label, value, tone=''}) { return <article className="metric"><span>{label}</span><strong className={tone}>{value}</strong></article> }
function DemandChart({result}) {
  const history = result.historical.slice(-26).map(x => ({date:x.date.slice(5), actual:x.weekly_sales}))
  const future = result.forecast.map(x => ({date:x.date.slice(5), forecast:x.forecast, lower:x.lower, upper:x.upper}))
  return <section className="panel chart-panel"><div className="section-title"><div><h2>Demand trajectory</h2><p>26 weeks of history and the next 4-week forecast</p></div><div className="legend"><i className="actual"/>Actual <i className="forecast"/>Forecast</div></div><ResponsiveContainer width="100%" height={340}><ComposedChart data={[...history,...future]} margin={{top:12,right:8,left:-18,bottom:2}}><CartesianGrid stroke="#21304b" vertical={false}/><XAxis dataKey="date" tick={{fill:'#91a2be',fontSize:11}} interval={4}/><YAxis tick={{fill:'#91a2be',fontSize:11}}/><Tooltip contentStyle={{background:'#101b31',border:'1px solid #31405e',borderRadius:10}}/><Area type="monotone" dataKey="upper" stroke="none" fill="#8b5cf6" fillOpacity={.18}/><Area type="monotone" dataKey="lower" stroke="none" fill="#101b31" fillOpacity={1}/><Line type="monotone" dataKey="actual" stroke="#67e8f9" strokeWidth={2.5} dot={false}/><Line type="monotone" dataKey="forecast" stroke="#a78bfa" strokeWidth={3} strokeDasharray="7 5" dot={{r:4,fill:'#a78bfa'}}/></ComposedChart></ResponsiveContainer></section>
}
function RiskCard({stockout}) { return <section className={`panel risk ${riskClass[stockout.risk_level]}`}><div className="section-title"><div><h2>Inventory position</h2><p>{stockout.risk_message}</p></div><b className="pill">{stockout.risk_level}</b></div><div className="inventory-grid"><Metric label="Current stock" value={`${stockout.current_stock.toLocaleString()} units`}/><Metric label="Weeks to stockout" value={stockout.weeks_until_stockout}/><Metric label="Lead time" value={`${stockout.lead_time_weeks} weeks`}/><Metric label="Order now" value={`${stockout.recommended_order_qty.toLocaleString()} units`}/></div></section> }
function Anomalies({items}) { return <section className="panel"><div className="section-title"><div><h2>Demand anomalies</h2><p>Statistically unusual sales periods</p></div><b>{items.length || 'No'} found</b></div>{items.length ? <div className="anomalies">{items.map(x=><div className="anomaly" key={x.date}><b>{x.direction === 'spike' ? '↑ Spike' : '↓ Drop'} · {x.date}</b><span>{x.actual_sales} units · {x.pct_deviation > 0 ? '+' : ''}{x.pct_deviation}% vs baseline</span></div>)}</div> : <div className="empty">Recent sales are within the expected range.</div>}</section> }

export default function App() {
  const [skus,setSkus]=useState([]), [regions,setRegions]=useState([]), [overview,setOverview]=useState([]), [selection,setSelection]=useState({sku_id:'',region:'All'}), [result,setResult]=useState(null), [busy,setBusy]=useState(false), [error,setError]=useState('')
  useEffect(()=>{ Promise.all([getSKUs(),getRegions(),getOverview()]).then(([a,b,c])=>{setSkus(a.skus);setRegions(b.regions);setOverview(c.categories);setSelection(s=>({...s,sku_id:a.skus[0]?.sku_id || ''}))}).catch(e=>setError(`Cannot reach the API: ${e.message}`)) },[])
  async function submit(){if(!selection.sku_id)return;setBusy(true);setError('');try{setResult(await runForecast({...selection,periods:4}))}catch(e){setError(e.message)}finally{setBusy(false)}}
  const total = result?.forecast.reduce((sum,x)=>sum+x.forecast,0)
  return <main><header><div className="brand"><div className="brandmark">F</div><div><h1>ForecastIQ</h1><p>Decision intelligence for inventory teams</p></div></div><div className="model">Prophet + XGBoost ensemble</div></header><div className="shell"><section className="hero"><div><span className="eyebrow">SUPPLY CHAIN CONTROL TOWER</span><h2>See demand shifts<br/><em>before they become stockouts.</em></h2><p>Forecast product demand, quantify inventory risk, and get an action your planning team can use today.</p></div><div className="selector"><label>Product<select value={selection.sku_id} onChange={e=>setSelection({...selection,sku_id:e.target.value})}>{skus.map(s=><option value={s.sku_id} key={s.sku_id}>{s.sku_id} — {s.product_name}</option>)}</select></label><label>Region<select value={selection.region} onChange={e=>setSelection({...selection,region:e.target.value})}>{regions.map(r=><option key={r}>{r}</option>)}</select></label><button onClick={submit} disabled={busy}>{busy ? 'Building forecast…' : 'Run forecast →'}</button></div></section>{error&&<div className="error">{error}</div>}{busy&&<div className="loading"><span/>Training the ensemble and calculating inventory risk…</div>}{result&&!busy&&<><section className="result-head"><div><span className="eyebrow">{result.category} · {result.region}</span><h2>{result.product_name}</h2></div><div className="metrics"><Metric label="4-week demand" value={`${Math.round(total).toLocaleString()} units`} tone="cyan"/><Metric label="Demand trend" value={`${result.trend_pct>0?'+':''}${result.trend_pct}%`} tone={result.trend_pct>=0?'green':'red'}/><Metric label="Ensemble MAPE" value={`${result.metrics.ensemble.mape}%`} tone="purple"/></div></section><section className="insight"><span>✦</span><div><b>AI PLANNING INSIGHT</b><p>{result.insight}</p></div></section><DemandChart result={result}/><div className="two-col"><RiskCard stockout={result.stockout}/><Anomalies items={result.anomalies}/></div></>}<section className="panel overview"><div className="section-title"><div><h2>Category demand mix</h2><p>Total historical sales across all regions</p></div></div><ResponsiveContainer width="100%" height={230}><BarChart data={overview}><CartesianGrid stroke="#21304b" vertical={false}/><XAxis dataKey="category" tick={{fill:'#91a2be',fontSize:11}}/><YAxis tick={{fill:'#91a2be',fontSize:11}}/><Tooltip contentStyle={{background:'#101b31',border:'1px solid #31405e',borderRadius:10}}/><Bar dataKey="total_sales" radius={[6,6,0,0]}>{overview.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Bar></BarChart></ResponsiveContainer></section></div></main>
}

